import mongoose from 'mongoose';
import dotenv from 'dotenv';
import WisdomBook from '../models/WisdomBook';

dotenv.config();

const sevenHabitsBook = {
  title: 'The 7 Habits of Highly Effective People',
  author: 'Stephen R. Covey',
  coverImage: 'https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg',
  categories: ['Productivity', 'Self-Help', 'Leadership'],
  themes: [
    { en: 'Character', ta: 'குணம்' },
    { en: 'Effectiveness', ta: 'செயல்திறன்' }
  ],
  overview: {
    en: 'Stephen R. Covey presents a holistic, integrated, principle-centered approach for solving personal and professional problems. With penetrating insights and pointed anecdotes, Covey reveals a step-by-step pathway for living with fairness, integrity, honesty, and human dignity.',
    ta: 'ஸ்டீபன் ஆர். கோவி தனிப்பட்ட மற்றும் தொழில்முறைப் பிரச்சினைகளைத் தீர்ப்பதற்கான ஒரு முழுமையான, ஒருங்கிணைந்த, கொள்கை மையப்படுத்தப்பட்ட அணுகுமுறையை முன்வைக்கிறார். ஆழமான நுண்ணறிவுகள் மற்றும் சுட்டிக்காட்டப்பட்ட நிகழ்வுகளுடன், நியாயம், நேர்மை மற்றும் மனித கண்ணியத்துடன் வாழ்வதற்கான படிப்படியான பாதையைக் கோவி வெளிப்படுத்துகிறார்.'
  },
  topQuotes: [
    { en: 'Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character; sow a character, reap a destiny.', ta: 'ஒரு எண்ணத்தை விதையுங்கள், ஒரு செயலை அறுவடை செய்யுங்கள்; ஒரு செயலை விதையுங்கள், ஒரு பழக்கத்தை அறுவடை செய்யுங்கள்; ஒரு பழக்கத்தை விதையுங்கள், ஒரு குணத்தை அறுவடை செய்யுங்கள்; ஒரு குணத்தை விதையுங்கள், ஒரு விதியை அறுவடை செய்யுங்கள்.' },
    { en: 'Most people do not listen with the intent to understand; they listen with the intent to reply.', ta: 'பெரும்பாலான மக்கள் புரிந்துகொள்ளும் நோக்கத்துடன் கேட்பதில்லை; அவர்கள் பதிலளிக்கும் நோக்கத்துடனேயே கேட்கிறார்கள்.' },
    { en: 'I am not a product of my circumstances. I am a product of my decisions.', ta: 'நான் எனது சூழ்நிலைகளின் தயாரிப்பு அல்ல. நான் எனது முடிவுகளின் தயாரிப்பு.' }
  ],
  lessons: [
    {
      lessonNumber: 1,
      title: { en: 'The Character Ethic vs. The Personality Ethic', ta: 'குண நன்னெறி vs ஆளுமை நன்னெறி' },
      explanation: { en: 'The Personality Ethic focuses on quick fixes, image, and social techniques (like public relations). The Character Ethic argues that true success depends on foundational principles like integrity, humility, and justice.', ta: 'ஆளுமை நன்னெறி விரைவான திருத்தங்கள், பிம்பம் மற்றும் சமூக நுட்பங்களில் (பொது உறவுகள் போன்றவை) கவனம் செலுத்துகிறது. நேர்மை, பணிவு மற்றும் நீதி போன்ற அடிப்படைக் கொள்கைகளைப் பொறுத்தே உண்மையான வெற்றி அமையும் என்று குண நன்னெறி வாதிடுகிறது.' },
      whyItMatters: { en: 'Personality techniques are manipulative and short-lived if they are not rooted in genuine character. You cannot "talk your way out" of a problem you "behaved your way into."', ta: 'ஆளுமை நுட்பங்கள் உண்மையான குணத்தில் வேரூன்றவில்லை என்றால் அவை கையாளுதல் தன்மைகொண்டவை மற்றும் குறுகிய காலம் வாழ்பவை. நீங்கள் "செயல்பட்டு நுழைந்த" ஒரு பிரச்சினையிலிருந்து உங்களால் "பேசி வெளியே வர" முடியாது.' },
      example: { en: 'Learning communication skills to appear empathetic (Personality Ethic) vs. actually doing the hard work to care about others genuinely (Character Ethic).', ta: 'பச்சாதாபமுள்ளவராகத் தோற்றமளிக்கத் தொடர்புத் திறன்களைக் கற்றுக்கொள்வது (ஆளுமை நன்னெறி) vs. உண்மையில் மற்றவர்கள் மீது அக்கறை கொள்ளக் கடினமான வேலையைச் செய்வது (குண நன்னெறி).' },
      actionStep: { en: 'Identify one area where you rely on superficial charm or "quick fixes." Commit to working on the underlying character flaw instead.', ta: 'நீங்கள் மேலோட்டமான வசீகரம் அல்லது "விரைவான திருத்தங்களை" நம்பியிருக்கும் ஒரு பகுதியைக் கண்டறியவும். அதற்குப் பதிலாக அடிப்படையான குணக் குறைபாட்டைச் சரிசெய்ய உறுதியளியுங்கள்.' },
      reflectionQuestion: { en: 'Are you trying to learn "tricks" to manage people better, instead of becoming the kind of person people naturally want to follow?', ta: 'மனிதர்கள் இயற்கையாகவே பின்பற்ற விரும்பும் ஒரு நபராக மாறுவதற்குப் பதிலாக, அவர்களைச் சிறப்பாக நிர்வகிக்க நீங்கள் "தந்திரங்களைக்" கற்றுக்கொள்ள முயற்சிக்கிறீர்களா?' }
    },
    {
      lessonNumber: 2,
      title: { en: 'The Paradigm Shift', ta: 'முன்மாதிரி மாற்றம் (Paradigm Shift)' },
      explanation: { en: 'A paradigm is the "lens" through which you see the world. Before you can change your behavior, you must change the way you see your situation.', ta: 'ஒரு முன்மாதிரி (Paradigm) என்பது நீங்கள் உலகைப் பார்க்கும் "லென்ஸ்" ஆகும். உங்கள் நடத்தையை மாற்றுவதற்கு முன், உங்கள் சூழ்நிலையை நீங்கள் பார்க்கும் விதத்தை நீங்கள் மாற்ற வேண்டும்.' },
      whyItMatters: { en: 'If you have the wrong map of a city, working harder or faster won\'t help you find your destination. You need the right map. Changing your paradigm changes everything.', ta: 'ஒரு நகரத்தின் தவறான வரைபடம் உங்களிடம் இருந்தால், கடினமாகவோ அல்லது வேகமாகவோ உழைப்பது உங்கள் இலக்கைக் கண்டறிய உதவாது. உங்களுக்குச் சரியான வரைபடம் தேவை. உங்கள் முன்மாதிரியை மாற்றுவது அனைத்தையும் மாற்றுகிறது.' },
      example: { en: 'Viewing a difficult coworker as an "enemy out to get you" (negative paradigm) vs. viewing them as a "person struggling with immense personal stress" (empathetic paradigm).', ta: 'ஒரு கடினமான சக ஊழியரை "உங்களை வீழ்த்த வந்த எதிரியாகப்" பார்ப்பது (எதிர்மறை முன்மாதிரி) vs. அவர்களை "அபரிமிதமான தனிப்பட்ட மன அழுத்தத்துடன் போராடும் நபராகப்" பார்ப்பது (பச்சாதாப முன்மாதிரி).' },
      actionStep: { en: 'Think of a person you currently dislike. Force yourself to write down three reasons why they might be acting that way from *their* perspective.', ta: 'தற்போது உங்களுக்குப் பிடிக்காத ஒருவரைப் பற்றிச் சிந்தியுங்கள். *அவர்களின்* கண்ணோட்டத்தில் அவர்கள் ஏன் அவ்வாறு நடந்துகொள்ளக் கூடும் என்பதற்கான மூன்று காரணங்களை எழுத உங்களை நீங்களே கட்டாயப்படுத்துங்கள்.' },
      reflectionQuestion: { en: 'Are you trying to change your results without first questioning the fundamental assumptions (your map) that lead to those results?', ta: 'அந்த முடிவுகளுக்கு வழிவகுக்கும் அடிப்படை அனுமானங்களை (உங்கள் வரைபடத்தை) முதலில் கேள்வி கேட்காமல் உங்கள் முடிவுகளை மாற்ற முயற்சிக்கிறீர்களா?' }
    },
    {
      lessonNumber: 3,
      title: { en: 'The Maturity Continuum', ta: 'முதிர்ச்சித் தொடர்ச்சி' },
      explanation: { en: 'Humans move from Dependence ("You must take care of me") to Independence ("I can do it myself") to Interdependence ("We can do something greater together").', ta: 'மனிதர்கள் சார்பு நிலையிலிருந்து ("நீங்கள் என்னைக் கவனித்துக் கொள்ள வேண்டும்") சுதந்திர நிலைக்குச் ("என்னால் அதைச் செய்ய முடியும்") சென்று, இறுதியாகச் சுழல்-சார்பு நிலைக்குச் ("நாம் ஒன்றாக இணைந்து சிறந்த ஒன்றைச் செய்ய முடியும்") செல்கிறார்கள்.' },
      whyItMatters: { en: 'Society glorifies independence as the highest goal. But true effectiveness requires interdependence—realizing that working cooperatively with others yields exponential results.', ta: 'சமூகம் சுதந்திரத்தை மிக உயர்ந்த இலக்காகப் பெருமைப்படுத்துகிறது. ஆனால் உண்மையான செயல்திறனுக்குச் சுழல்-சார்பு தேவை—மற்றவர்களுடன் இணைந்து செயல்படுவது அபரிமிதமான விளைவுகளைத் தரும் என்பதை உணர்தல்.' },
      example: { en: 'A talented programmer who refuses to work with a team (Independence) will never build a massive software company like a programmer who collaborates well with designers and marketers (Interdependence).', ta: 'குழுவுடன் இணைந்து பணியாற்ற மறுக்கும் திறமையான புரோகிராமர் (சுதந்திரம்), வடிவமைப்பாளர்கள் மற்றும் சந்தைப்படுத்துபவர்களுடன் நன்றாக ஒத்துழைக்கும் ஒரு புரோகிராமரைப் போல (சுழல்-சார்பு) ஒருபோதும் ஒரு பெரிய மென்பொருள் நிறுவனத்தை உருவாக்க மாட்டார்.' },
      actionStep: { en: 'Acknowledge where you are stuck in "Dependence" (blaming others) or overly attached to "Independence" (refusing help). Ask someone for collaborative input today.', ta: '"சார்பு நிலையில்" (மற்றவர்களைக் குறை கூறுதல்) நீங்கள் எங்குச் சிக்கியிருக்கிறீர்கள் அல்லது "சுதந்திரத்துடன்" (உதவியை மறுத்தல்) அதிகமாக இணைக்கப்பட்டிருக்கிறீர்கள் என்பதை ஒப்புக்கொள்ளுங்கள். இன்று கூட்டான உள்ளீட்டிற்கு யாரிடமாவது உதவி கேளுங்கள்.' },
      reflectionQuestion: { en: 'Do you view asking for help or collaborating as a sign of weakness, limiting your ultimate potential?', ta: 'உதவி கேட்பதையோ அல்லது ஒத்துழைப்பதையோ பலவீனத்தின் அறிகுறியாகப் பார்த்து, உங்களின் இறுதித் திறனை நீங்களே கட்டுப்படுத்துகிறீர்களா?' }
    },
    {
      lessonNumber: 4,
      title: { en: 'Habit 1: Be Proactive', ta: 'பழக்கம் 1: முன்கூட்டியே செயல்படுங்கள் (Be Proactive)' },
      explanation: { en: 'Being proactive means taking responsibility for your life. Proactive people recognize that their behavior is a product of their conscious choices, based on values, rather than a product of their conditions, based on feeling.', ta: 'முன்கூட்டியே செயல்படுவது என்பது உங்கள் வாழ்க்கைக்குப் பொறுப்பேற்பதாகும். முன்கூட்டியே செயல்படும் மனிதர்கள், தங்களின் நடத்தை உணர்வின் அடிப்படையிலான நிலைமைகளின் விளைவல்ல, அது மதிப்புகளின் அடிப்படையிலான தங்களின் நனவான தேர்வுகளின் விளைவு என்பதை அங்கீகரிக்கின்றனர்.' },
      whyItMatters: { en: 'Between stimulus and response, you have the freedom to choose. If you are reactive, the environment controls you. If you are proactive, you control your response to the environment.', ta: 'தூண்டுதலுக்கும் பதிலுக்கும் இடையில், தேர்ந்தெடுக்கும் சுதந்திரம் உங்களுக்கு உள்ளது. நீங்கள் எதிர்வினையாற்றுபவராக (Reactive) இருந்தால், சூழல் உங்களைக் கட்டுப்படுத்துகிறது. நீங்கள் முன்கூட்டியே செயல்படுபவராக இருந்தால், சூழலுக்கான உங்களின் பதிலடி உங்களின் கட்டுப்பாட்டில் இருக்கும்.' },
      example: { en: 'Reactive: "He makes me so mad." Proactive: "I control my own feelings; I am choosing to let his behavior upset me, and I can choose differently."', ta: 'எதிர்வினை: "அவன் என்னை மிகவும் கோபப்படுத்துகிறான்." முன்கூட்டியே செயல்படுவது: "எனது சொந்த உணர்வுகளை நான் கட்டுப்படுத்துகிறேன்; அவனது நடத்தை என்னை வருத்தப்படுத்த நான் தேர்வு செய்கிறேன், நான் வித்தியாசமாகவும் தேர்வு செய்யலாம்."' },
      actionStep: { en: 'Listen to your language today. Catch yourself saying reactive phrases ("I can\'t", "I have to") and replace them with proactive ones ("I choose to", "I will").', ta: 'இன்று உங்கள் மொழியைக் கேளுங்கள். எதிர்வினைச் சொற்றொடர்களைச் சொல்லும்போது ("என்னால் முடியாது", "நான் செய்ய வேண்டும்") உங்களைப் பிடித்துக்கொண்டு, அவற்றை முன்கூட்டியே செயல்படும் சொற்றொடர்களால் ("நான் தேர்வு செய்கிறேன்", "நான் செய்வேன்") மாற்றவும்.' },
      reflectionQuestion: { en: 'Are you handing over your emotional remote control to the weather, the traffic, or your boss\'s bad mood?', ta: 'உங்களின் உணர்ச்சிகரமான ரிமோட் கண்ட்ரோலை வானிலை, போக்குவரத்து அல்லது உங்கள் முதலாளியின் மோசமான மனநிலைக்கு நீங்கள் விட்டுக்கொடுக்கிறீர்களா?' }
    },
    {
      lessonNumber: 5,
      title: { en: 'Circle of Concern vs. Circle of Influence', ta: 'கவலை வட்டம் vs செல்வாக்கு வட்டம்' },
      explanation: { en: 'The Circle of Concern includes everything you care about (the economy, the weather, politics). The Circle of Influence includes only the things you can actually control (your attitude, your skills, your actions).', ta: 'கவலை வட்டத்தில் நீங்கள் அக்கறை கொள்ளும் அனைத்தும் (பொருளாதாரம், வானிலை, அரசியல்) அடங்கும். செல்வாக்கு வட்டத்தில் உங்களால் உண்மையில் கட்டுப்படுத்தக் கூடிய விஷயங்கள் (உங்கள் அணுகுமுறை, உங்கள் திறன்கள், உங்கள் செயல்கள்) மட்டுமே அடங்கும்.' },
      whyItMatters: { en: 'Reactive people focus on the Circle of Concern, wasting energy on things they cannot change. Proactive people focus on their Circle of Influence, which causes their influence to expand.', ta: 'எதிர்வினையாற்றும் மனிதர்கள் கவலை வட்டத்தில் கவனம் செலுத்துகிறார்கள், மாற்ற முடியாத விஷயங்களில் ஆற்றலை வீணாக்குகிறார்கள். முன்கூட்டியே செயல்படும் மனிதர்கள் தங்களின் செல்வாக்கு வட்டத்தில் கவனம் செலுத்துகிறார்கள், இது அவர்களின் செல்வாக்கை விரிவுபடுத்துகிறது.' },
      example: { en: 'Instead of complaining that the job market is terrible (Circle of Concern), taking a course to learn a highly in-demand skill (Circle of Influence).', ta: 'வேலை வாய்ப்புச் சந்தை மோசமாக உள்ளது என்று குறை கூறுவதற்குப் பதிலாக (கவலை வட்டம்), அதிகத் தேவையுள்ள திறனைக் கற்றுக்கொள்ள ஒரு படிப்பை மேற்கொள்வது (செல்வாக்கு வட்டம்).' },
      actionStep: { en: 'Identify a major stressor in your life right now. Write down exactly what aspects of it are in your Circle of Influence, and ignore the rest.', ta: 'தற்போது உங்கள் வாழ்க்கையில் ஒரு முக்கிய மன அழுத்தத்தைக் கண்டறியவும். அதன் எந்த அம்சங்கள் உங்களின் செல்வாக்கு வட்டத்தில் உள்ளன என்பதைத் துல்லியமாக எழுதுங்கள், மற்றவற்றைப் புறக்கணிக்கவும்.' },
      reflectionQuestion: { en: 'Are you exhausting yourself by trying to control the uncontrollable, while neglecting the very things you have power over?', ta: 'கட்டுப்படுத்த முடியாதவற்றைக் கட்டுப்படுத்த முயற்சிப்பதன் மூலம் உங்களை நீங்களே சோர்வடையச் செய்கிறீர்களா, அதே நேரத்தில் உங்கள் கட்டுப்பாட்டில் உள்ள விஷயங்களை நீங்கள் புறக்கணிக்கிறீர்களா?' }
    },
    {
      lessonNumber: 6,
      title: { en: 'Habit 2: Begin with the End in Mind', ta: 'பழக்கம் 2: முடிவை மனதில் கொண்டு தொடங்குங்கள் (Begin with the End in Mind)' },
      explanation: { en: 'This habit is based on the principle that all things are created twice: first in the mind (mental creation), and second in physical reality (physical creation).', ta: 'அனைத்து விஷயங்களும் இரண்டு முறை உருவாக்கப்படுகின்றன என்ற கொள்கையின் அடிப்படையில் இந்தப் பழக்கம் அமைந்துள்ளது: முதலில் மனதில் (மன உருவாக்கம்), மற்றும் இரண்டாவது பௌதீக யதார்த்தத்தில் (உடல் உருவாக்கம்).' },
      whyItMatters: { en: 'If you don\'t consciously design your own life, you will live by default, playing out the scripts written for you by society, family, or circumstances. You might climb the ladder of success only to realize it\'s leaning against the wrong wall.', ta: 'உங்களின் சொந்த வாழ்க்கையை நீங்கள் பிரக்ஞையுடன் வடிவமைக்கவில்லை என்றால், சமூகம், குடும்பம் அல்லது சூழ்நிலைகளால் உங்களுக்காக எழுதப்பட்ட திரைக்கதைகளில் நடித்து, நீங்கள் இயல்பாகவே வாழ்வீர்கள். நீங்கள் வெற்றியின் ஏணியில் ஏறிய பிறகு, அது தவறான சுவரில் சாய்ந்திருப்பதை நீங்கள் உணரக்கூடும்.' },
      example: { en: 'A carpenter blueprinting exactly what a house will look like down to the millimeter before ever touching a hammer or a piece of wood.', ta: 'ஒரு தச்சர் சுத்தியலையோ அல்லது மரத்துண்டையோ தொடுவதற்கு முன்பே, ஒரு வீடு எப்படி இருக்கும் என்பதை மில்லிமீட்டர் வரை துல்லியமாக வரைபடமாக்குவது.' },
      actionStep: { en: 'Imagine you are at your own funeral. What do you want your family, friends, and coworkers to say about you? Write it down.', ta: 'உங்களின் சொந்த இறுதிச் சடங்கில் நீங்கள் இருப்பதாகக் கற்பனை செய்து பாருங்கள். உங்கள் குடும்பத்தினர், நண்பர்கள் மற்றும் சக ஊழியர்கள் உங்களைப் பற்றி என்ன சொல்ல வேண்டும் என்று விரும்புகிறீர்கள்? அதை எழுதுங்கள்.' },
      reflectionQuestion: { en: 'Are you working incredibly hard every day without actually knowing what your ultimate destination is?', ta: 'உங்களின் இறுதி இலக்கு என்னவென்று உண்மையில் தெரியாமலேயே ஒவ்வொரு நாளும் நம்பமுடியாத அளவிற்கு நீங்கள் கடினமாக உழைக்கிறீர்களா?' }
    },
    {
      lessonNumber: 7,
      title: { en: 'Write a Personal Mission Statement', ta: 'தனிப்பட்ட பணி அறிக்கையை எழுதுங்கள்' },
      explanation: { en: 'A personal mission statement focuses on what you want to be (character) and to do (contributions and achievements) and on the values or principles upon which being and doing are based.', ta: 'ஒரு தனிப்பட்ட பணி அறிக்கை (Personal Mission Statement) நீங்கள் என்னவாக இருக்க விரும்புகிறீர்கள் (குணம்) மற்றும் என்ன செய்ய விரும்புகிறீர்கள் (பங்களிப்புகள் மற்றும் சாதனைகள்) மற்றும் எந்த மதிப்புகள் அல்லது கொள்கைகளின் அடிப்படையில் நீங்கள் இருக்கிறீர்கள் மற்றும் செயல்படுகிறீர்கள் என்பதில் கவனம் செலுத்துகிறது.' },
      whyItMatters: { en: 'Your mission statement becomes your personal constitution. It gives you a solid, unchanging core that allows you to weather the rapid changes and stresses of life without losing your way.', ta: 'உங்கள் பணி அறிக்கை உங்களின் தனிப்பட்ட அரசியலமைப்பாக மாறுகிறது. இது உங்களுக்கு உறுதியான, மாறாத மையப்பகுதியை வழங்குகிறது, இது உங்கள் வழியை இழக்காமல் வாழ்க்கையின் விரைவான மாற்றங்களையும் அழுத்தங்களையும் சமாளிக்க உங்களை அனுமதிக்கிறது.' },
      example: { en: '"My mission is to listen with empathy, lead with courage, and create software that makes human connection easier, while never sacrificing time with my family."', ta: '"பச்சாதாபத்துடன் கேட்பதும், தைரியத்துடன் வழிநடத்துவதும், மனிதத் தொடர்பை எளிதாக்கும் மென்பொருளை உருவாக்குவதும், அதே நேரத்தில் என் குடும்பத்துடனான நேரத்தை ஒருபோதும் தியாகம் செய்யாமல் இருப்பதுமே எனது பணியாகும்."' },
      actionStep: { en: 'Draft the first version of your Personal Mission Statement today. It doesn\'t have to be perfect; just write down 3-5 core principles you want to live by.', ta: 'இன்று உங்களின் தனிப்பட்ட பணி அறிக்கையின் முதல் வரைவைத் தயாரிக்கவும். அது கச்சிதமாக இருக்க வேண்டியதில்லை; நீங்கள் வாழ விரும்பும் 3-5 முக்கியக் கொள்கைகளை மட்டும் எழுதுங்கள்.' },
      reflectionQuestion: { en: 'When faced with a tough moral or career choice, do you have a written constitution to guide you, or do you just guess?', ta: 'கடினமான தார்மீக அல்லது தொழில் தேர்வினை எதிர்கொள்ளும்போது, உங்களை வழிநடத்த ஒரு எழுதப்பட்ட அரசியலமைப்பு உங்களிடம் இருக்கிறதா, அல்லது நீங்கள் வெறுமனே யூகிக்கிறீர்களா?' }
    },
    {
      lessonNumber: 8,
      title: { en: 'Habit 3: Put First Things First', ta: 'பழக்கம் 3: முதன்மையான விஷயங்களுக்கு முன்னுரிமை கொடுங்கள் (Put First Things First)' },
      explanation: { en: 'Habit 1 says "You are the creator." Habit 2 is the mental creation. Habit 3 is the physical creation—it is the exercise of independent will to become principle-centered by managing your time around your priorities.', ta: 'பழக்கம் 1 "நீங்களே உருவாக்குபவர்" என்று கூறுகிறது. பழக்கம் 2 என்பது மன உருவாக்கம். பழக்கம் 3 என்பது உடல் உருவாக்கம்—இது உங்களின் முன்னுரிமைகளைச் சுற்றி உங்கள் நேரத்தை நிர்வகிப்பதன் மூலம் கொள்கை மையமாக மாறுவதற்குச் சுதந்திரமான விருப்பத்தைப் பயன்படுத்துவதாகும்.' },
      whyItMatters: { en: 'It\'s easy to get caught up in the "thick of thin things." Effective management is putting first things first. Leadership decides what the "first things" are; management puts them first day by day.', ta: '"மெல்லிய விஷயங்களின் தடிமனில்" சிக்கிக்கொள்வது எளிது. பயனுள்ள நிர்வாகம் என்பது முதன்மையான விஷயங்களுக்கு முன்னுரிமை கொடுப்பதாகும். "முதன்மையான விஷயங்கள்" எவை என்பதைத் தலைமை தீர்மானிக்கிறது; நிர்வாகம் அவற்றை நாளுக்கு நாள் முதலில் வைக்கிறது.' },
      example: { en: 'Declining an invitation to a casual networking event because you have scheduled that time to have a deep, meaningful dinner with your spouse.', ta: 'உங்கள் வாழ்க்கைத்துணையுடன் ஆழமான, அர்த்தமுள்ள இரவு உணவைச் சாப்பிட அந்த நேரத்தை நீங்கள் ஒதுக்கியிருப்பதால், சாதாரண நெட்வொர்க்கிங் நிகழ்விற்கான அழைப்பை நிராகரிப்பது.' },
      actionStep: { en: 'Look at your calendar for next week. Schedule your "First Things" (family time, exercise, deep work) BEFORE you schedule meetings and obligations to others.', ta: 'அடுத்த வாரத்திற்கான உங்கள் காலெண்டரைப் பாருங்கள். கூட்டங்கள் மற்றும் மற்றவர்களுக்கான கடமைகளை நீங்கள் திட்டமிடுவதற்கு முன்பாக, உங்களின் "முதன்மையான விஷயங்களை" (குடும்ப நேரம், உடற்பயிற்சி, ஆழமான வேலை) திட்டமிடுங்கள்.' },
      reflectionQuestion: { en: 'Are you prioritizing your schedule, or are you scheduling your priorities?', ta: 'நீங்கள் உங்களின் அட்டவணைக்கு முன்னுரிமை அளிக்கிறீர்களா, அல்லது உங்களின் முன்னுரிமைகளை அட்டவணையிடுகிறீர்களா?' }
    },
    {
      lessonNumber: 9,
      title: { en: 'The Time Management Matrix (Quadrant II)', ta: 'நேர மேலாண்மை அணி (கால்பகுதி II)' },
      explanation: { en: 'Activities can be categorized by Urgency and Importance into four quadrants. Q1 (Urgent/Important), Q2 (Not Urgent/Important), Q3 (Urgent/Not Important), and Q4 (Not Urgent/Not Important).', ta: 'செயல்பாடுகளை அவசரம் மற்றும் முக்கியத்துவம் ஆகியவற்றின் அடிப்படையில் நான்கு கால்பகுதிகளாக (Quadrants) வகைப்படுத்தலாம். Q1 (அவசரம்/முக்கியம்), Q2 (அவசரம் இல்லை/முக்கியம்), Q3 (அவசரம்/முக்கியம் இல்லை), மற்றும் Q4 (அவசரம் இல்லை/முக்கியம் இல்லை).' },
      whyItMatters: { en: 'Highly effective people spend most of their time in Quadrant II (Not Urgent but Important). This includes planning, relationship building, exercise, and preventative maintenance. Ignoring Q2 creates a crisis-filled Q1.', ta: 'மிகவும் திறமையான மனிதர்கள் தங்கள் நேரத்தின் பெரும்பகுதியைக் கால்பகுதி II-ல் (அவசரமில்லை ஆனால் முக்கியமானது) செலவிடுகிறார்கள். இதில் திட்டமிடல், உறவை உருவாக்குதல், உடற்பயிற்சி மற்றும் தடுப்புப் பராமரிப்பு ஆகியவை அடங்கும். Q2-ஐப் புறக்கணிப்பது நெருக்கடி நிறைந்த Q1-ஐ உருவாக்குகிறது.' },
      example: { en: 'Changing the oil in your car (Q2) prevents the engine from blowing up on the highway (Q1). Exercising daily (Q2) prevents a heart attack (Q1).', ta: 'உங்கள் காரில் எண்ணெயை மாற்றுவது (Q2) நெடுஞ்சாலையில் என்ஜின் வெடிப்பதைத் தடுக்கிறது (Q1). தினமும் உடற்பயிற்சி செய்வது (Q2) மாரடைப்பைத் தடுக்கிறது (Q1).' },
      actionStep: { en: 'Identify one Quadrant II activity (important but not urgent) that you have been neglecting. Schedule 30 minutes to do it tomorrow.', ta: 'நீங்கள் புறக்கணித்து வரும் ஒரு கால்பகுதி II செயல்பாட்டை (முக்கியமானது ஆனால் அவசரமில்லை) கண்டறியவும். நாளை அதைச் செய்ய 30 நிமிடங்களை ஒதுக்குங்கள்.' },
      reflectionQuestion: { en: 'Are you spending your life putting out fires in Quadrant 1, rather than preventing the fires in Quadrant 2?', ta: 'கால்பகுதி 2-ல் உள்ள தீயைத் தடுப்பதற்குப் பதிலாக, கால்பகுதி 1-ல் உள்ள தீயை அணைப்பதிலேயே உங்கள் வாழ்க்கையைச் செலவிடுகிறீர்களா?' }
    },
    {
      lessonNumber: 10,
      title: { en: 'The Emotional Bank Account', ta: 'உணர்ச்சிகரமான வங்கிக் கணக்கு' },
      explanation: { en: 'An Emotional Bank Account represents the amount of trust built up in a relationship. You make deposits through courtesy, kindness, and keeping promises. You make withdrawals through disrespect and breaking trust.', ta: 'ஒரு உணர்ச்சிகரமான வங்கிக் கணக்கு என்பது ஒரு உறவில் கட்டமைக்கப்பட்ட நம்பிக்கையின் அளவைக் குறிக்கிறது. மரியாதை, கருணை மற்றும் வாக்குறுதிகளைக் காப்பாற்றுதல் ஆகியவற்றின் மூலம் நீங்கள் வைப்புகளை (Deposits) செய்கிறீர்கள். அவமரியாதை மற்றும் நம்பிக்கையை உடைப்பதன் மூலம் நீங்கள் திரும்பப் பெறுதல்களை (Withdrawals) செய்கிறீர்கள்.' },
      whyItMatters: { en: 'If your account is in the positive, minor mistakes are easily forgiven. If your account is overdrawn, every word is analyzed and every action is viewed with suspicion.', ta: 'உங்கள் கணக்கு நேர்மறையாக இருந்தால், சிறிய தவறுகள் எளிதில் மன்னிக்கப்படும். உங்கள் கணக்கில் வரம்பை மீறித் தொகை எடுக்கப்பட்டால் (Overdrawn), ஒவ்வொரு வார்த்தையும் பகுப்பாய்வு செய்யப்பட்டு, ஒவ்வொரு செயலும் சந்தேகத்துடன் பார்க்கப்படும்.' },
      example: { en: 'Listening deeply to your child without judging them is a massive deposit. Snapping at them because you are stressed from work is a withdrawal.', ta: 'உங்கள் குழந்தையை மதிப்பிடாமல் ஆழமாகக் கேட்பது ஒரு மிகப்பெரிய வைப்பு. நீங்கள் வேலையிலிருந்து மன அழுத்தத்தில் இருப்பதால் அவர்களிடம் கத்துவது ஒரு திரும்பப் பெறுதல்.' },
      actionStep: { en: 'Think of one important relationship where your account might be low. Make a deliberate "deposit" today—a sincere compliment, an apology, or an act of service.', ta: 'உங்களின் கணக்கு குறைவாக இருக்கக்கூடிய ஒரு முக்கியமான உறவைப் பற்றிச் சிந்தியுங்கள். இன்று வேண்டுமென்றே ஒரு "வைப்பு" செய்யுங்கள்—உண்மையான பாராட்டு, மன்னிப்பு அல்லது ஒரு சேவை.' },
      reflectionQuestion: { en: 'Are you trying to withdraw trust and cooperation from relationships where you haven\'t made any deposits in months?', ta: 'பல மாதங்களாக நீங்கள் எந்த வைப்பும் செய்யாத உறவுகளிலிருந்து நம்பிக்கையையும் ஒத்துழைப்பையும் திரும்பப் பெற முயற்சிக்கிறீர்களா?' }
    },
    {
      lessonNumber: 11,
      title: { en: 'Habit 4: Think Win-Win', ta: 'பழக்கம் 4: வெற்றி-வெற்றி எனச் சிந்தியுங்கள் (Think Win-Win)' },
      explanation: { en: 'Win-Win is a frame of mind and heart that constantly seeks mutual benefit in all human interactions. It means agreements or solutions are mutually beneficial and mutually satisfying.', ta: 'வெற்றி-வெற்றி (Win-Win) என்பது அனைத்து மனிதத் தொடர்புகளிலும் தொடர்ந்து பரஸ்பர நன்மைகளைத் தேடும் மன மற்றும் இதயச் சட்டமாகும். உடன்பாடுகள் அல்லது தீர்வுகள் பரஸ்பர நன்மை பயக்கும் மற்றும் பரஸ்பரத் திருப்தியளிக்கும் என்பதை இது குறிக்கிறது.' },
      whyItMatters: { en: 'Most people think in terms of Win-Lose (I get my way, you don\'t). This destroys relationships long-term. Win-Win sees life as a cooperative arena, not a competitive one. There is plenty for everyone.', ta: 'பெரும்பாலான மக்கள் வெற்றி-தோல்வி (என் வழி எனக்குக் கிடைக்கிறது, உங்களுக்கு இல்லை) என்றே நினைக்கிறார்கள். இது நீண்டகால அடிப்படையில் உறவுகளை அழிக்கிறது. வெற்றி-வெற்றி வாழ்க்கையை ஒரு கூட்டுக்களமாகப் பார்க்கிறது, போட்டி நிறைந்ததாக அல்ல. அனைவருக்கும் போதுமான அளவு உள்ளது.' },
      example: { en: 'A manager negotiating a salary with an employee: Instead of trying to pay the absolute minimum (Win-Lose), tying a higher salary to specific performance metrics so both the company and the employee prosper (Win-Win).', ta: 'ஒரு ஊழியருடன் சம்பளப் பேச்சுவார்த்தை நடத்தும் ஒரு மேலாளர்: முழுமையான குறைந்தபட்ச ஊதியத்தை வழங்க முயற்சிப்பதற்குப் பதிலாக (வெற்றி-தோல்வி), அதிகச் சம்பளத்தைக் குறிப்பிட்ட செயல்திறன் அளவீடுகளுடன் இணைப்பது, இதனால் நிறுவனமும் ஊழியரும் செழிப்பார்கள் (வெற்றி-வெற்றி).' },
      actionStep: { en: 'In your next negotiation or conflict, explicitly state: "I want to find a solution that works great for both of us. If we can\'t find one, let\'s agree to walk away rather than one of us losing."', ta: 'உங்களின் அடுத்தப் பேச்சுவார்த்தை அல்லது மோதலில், வெளிப்படையாகக் கூறுங்கள்: "நம் இருவருக்கும் சிறப்பாக வேலை செய்யும் ஒரு தீர்வை நான் கண்டறிய விரும்புகிறேன். நம்மால் அதைக் கண்டுபிடிக்க முடியாவிட்டால், நம்மில் ஒருவர் தோற்பதற்குப் பதிலாக விலகிச் செல்ல ஒப்புக்கொள்வோம்."' },
      reflectionQuestion: { en: 'Do you secretly feel that for you to succeed, someone else must fail?', ta: 'நீங்கள் வெற்றிபெற, வேறு ஒருவர் தோல்வியடைய வேண்டும் என்று நீங்கள் ரகசியமாக உணர்கிறீர்களா?' }
    },
    {
      lessonNumber: 12,
      title: { en: 'Abundance Mentality vs. Scarcity Mentality', ta: 'ஏராளமான மனநிலை vs பற்றாக்குறை மனநிலை' },
      explanation: { en: 'The Scarcity Mentality sees life as having only so much, as though there were only one pie out there. The Abundance Mentality flows out of a deep inner sense of personal worth and security. It is the paradigm that there is plenty out there for everybody.', ta: 'பற்றாக்குறை மனநிலை (Scarcity Mentality) வாழ்க்கையில் குறைந்த அளவே உள்ளது என்று பார்க்கிறது, அங்கு ஒரு பை (Pie) மட்டுமே இருப்பது போல. ஏராளமான மனநிலை (Abundance Mentality) தனிப்பட்ட மதிப்பு மற்றும் பாதுகாப்பின் ஆழமான உள் உணர்விலிருந்து வெளிப்படுகிறது. அனைவருக்கும் அங்கே நிறைய இருக்கிறது என்ற முன்மாதிரி இது.' },
      whyItMatters: { en: 'People with a Scarcity Mentality have a very hard time sharing recognition, power, or profit. They harbor secret hopes that others will fail. Abundance Mentality creates highly synergistic, joyful teams.', ta: 'பற்றாக்குறை மனநிலை கொண்டவர்கள் அங்கீகாரம், அதிகாரம் அல்லது லாபத்தைப் பகிர்ந்துகொள்வதில் மிகவும் சிரமப்படுகிறார்கள். மற்றவர்கள் தோல்வியடைவார்கள் என்ற ரகசிய நம்பிக்கைகளை அவர்கள் வளர்க்கிறார்கள். ஏராளமான மனநிலை மிகவும் ஒருங்கிணைந்த, மகிழ்ச்சியான குழுக்களை உருவாக்குகிறது.' },
      example: { en: 'A salesperson hoarding leads and hiding best practices from their team (Scarcity) vs. a salesperson openly teaching their techniques to the team so everyone makes more money (Abundance).', ta: 'ஒரு விற்பனையாளர் லீட்களைப் (leads) பதுக்கிவைப்பது மற்றும் அவர்களின் சிறந்த நடைமுறைகளைத் தங்களின் குழுவிடமிருந்து மறைப்பது (பற்றாக்குறை) vs. ஒரு விற்பனையாளர் தனது நுட்பங்களை அணிக்கு வெளிப்படையாகக் கற்பிப்பது, அதனால் அனைவரும் அதிகப் பணம் சம்பாதிப்பார்கள் (ஏராளம்).' },
      actionStep: { en: 'Identify a competitor or peer who recently succeeded. Send them a genuine message of congratulations today, fully celebrating their success without any jealousy.', ta: 'சமீபத்தில் வெற்றிபெற்ற ஒரு போட்டியாளர் அல்லது சகாவைக் கண்டறியவும். இன்று அவர்களுக்கு உண்மையான வாழ்த்துச் செய்தியை அனுப்புங்கள், எந்தப் பொறாமையும் இல்லாமல் அவர்களின் வெற்றியை முழுமையாகக் கொண்டாடுங்கள்.' },
      reflectionQuestion: { en: 'Does another person\'s success make you feel like something has been taken away from you?', ta: 'மற்றொரு நபரின் வெற்றி, உங்களிடமிருந்து ஏதோ பறிக்கப்பட்டது போல் உங்களை உணர வைக்கிறதா?' }
    },
    {
      lessonNumber: 13,
      title: { en: 'Habit 5: Seek First to Understand, Then to Be Understood', ta: 'பழக்கம் 5: முதலில் புரிந்துகொள்ள முற்படுங்கள், பின்னர் புரிந்து கொள்ளப்பட முற்படுங்கள்' },
      explanation: { en: 'This is the most important principle of interpersonal relations. We typically seek first to be understood. We read our autobiography into other people\'s lives and prescribe solutions before diagnosing the problem.', ta: 'ஒருவருக்கொருவர் இடையேயான உறவுகளின் மிக முக்கியமான கொள்கை இது. நாம் பொதுவாக முதலில் மற்றவர்கள் நம்மைப் புரிந்துகொள்ள வேண்டும் என்றே முற்படுகிறோம். மற்றவர்களின் வாழ்க்கையில் நமது சுயசரிதையைப் படிக்கிறோம், மேலும் பிரச்சினையைக் கண்டறிவதற்கு முன்பே தீர்வுகளைப் பரிந்துரைக்கிறோம்.' },
      whyItMatters: { en: 'If a doctor gave you a prescription without listening to your symptoms, you would never trust them. Yet, we do this in communication constantly. You cannot influence someone until they feel deeply understood.', ta: 'உங்களின் அறிகுறிகளைக் கேட்காமல் ஒரு மருத்துவர் உங்களுக்கு மருந்து எழுதிக் கொடுத்தால், நீங்கள் அவர்களை ஒருபோதும் நம்ப மாட்டீர்கள். ஆயினும்கூட, தகவல் தொடர்புகளில் இதை நாம் தொடர்ந்து செய்கிறோம். ஒருவரை ஆழமாகப் புரிந்துகொண்டதாக அவர்கள் உணரும் வரை உங்களால் அவர்கள் மீது செல்வாக்குச் செலுத்த முடியாது.' },
      example: { en: 'A teenager says "School is stupid." Instead of saying "You need school to get a job!" (Prescribing), you say "It sounds like you are feeling really frustrated with your classes right now." (Understanding).', ta: 'ஒரு பதின்ம வயதினர் "பள்ளி முட்டாள்தனமானது" என்று கூறுகிறார். "உனக்கு வேலை கிடைக்கப் பள்ளி தேவை!" (பரிந்துரைத்தல்) என்று கூறுவதற்குப் பதிலாக, "நீ இப்போது உனது வகுப்புகளில் மிகவும் விரக்தியடைந்திருப்பதாகத் தெரிகிறது" என்று நீங்கள் கூறுங்கள் (புரிந்துகொள்ளுதல்).' },
      actionStep: { en: 'In your next conversation, practice Empathic Listening. Do not offer advice, do not share your own story, and do not judge. Just reflect back their feelings and meaning until they say "Yes, exactly!"', ta: 'உங்களின் அடுத்த உரையாடலில், பச்சாதாபத்துடன் கேட்பதைப் பயிற்சி செய்யுங்கள். ஆலோசனை வழங்க வேண்டாம், உங்கள் சொந்தக் கதையைப் பகிர வேண்டாம், மற்றும் மதிப்பிட வேண்டாம். அவர்கள் "ஆம், சரியாக!" என்று சொல்லும் வரை அவர்களின் உணர்வுகளையும் அர்த்தத்தையும் மட்டும் பிரதிபலிக்கவும்.' },
      reflectionQuestion: { en: 'While someone is talking to you, are you actually listening to them, or are you just mentally preparing your reply?', ta: 'யாராவது உங்களிடம் பேசும்போது, நீங்கள் உண்மையில் அவர்கள் சொல்வதைக் கேட்கிறீர்களா, அல்லது உங்களின் பதிலுக்காக மனதளவில் தயாராகிறீர்களா?' }
    },
    {
      lessonNumber: 14,
      title: { en: 'Empathic Listening', ta: 'பச்சாதாபத்துடன் கேட்டல்' },
      explanation: { en: 'Empathic listening gets inside another person\'s frame of reference. You look out through it, you see the world the way they see the world, you understand their paradigm, you understand how they feel.', ta: 'பச்சாதாபத்துடன் கேட்பது என்பது மற்றொரு நபரின் குறிப்புச் சட்டகத்திற்குள் நுழைகிறது. நீங்கள் அதன் வழியாக வெளியே பார்க்கிறீர்கள், அவர்கள் உலகைப் பார்க்கும் விதத்தில் உலகைப் பார்க்கிறீர்கள், அவர்களின் முன்மாதிரியைப் புரிந்துகொள்கிறீர்கள், அவர்கள் எப்படி உணர்கிறார்கள் என்பதைப் புரிந்துகொள்கிறீர்கள்.' },
      whyItMatters: { en: 'Empathic listening provides "psychological air." When a person is gasping for air, they cannot listen to your advice. Once they feel understood, their defensiveness drops, and true problem-solving can begin.', ta: 'பச்சாதாபத்துடன் கேட்பது "உளவியல் காற்றை" வழங்குகிறது. ஒரு நபர் மூச்சுத் திணறும்போது, அவர்கள் உங்கள் ஆலோசனையைக் கேட்க முடியாது. அவர்கள் புரிந்துகொள்ளப்பட்டதாக உணர்ந்தவுடன், அவர்களின் தற்காப்புத் தன்மை குறைகிறது, மேலும் உண்மையான பிரச்சினையைத் தீர்க்கும் பணி தொடங்கும்.' },
      example: { en: 'Not just repeating words back like a parrot, but rephrasing the content and reflecting the feeling: "You feel neglected (feeling) because I have been working late every night this week (content)." ', ta: 'கிளியைப் போல வார்த்தைகளைத் திரும்பத் திரும்பச் சொல்வது மட்டுமல்லாமல், உள்ளடக்கத்தை மறுபரிசீலனை செய்து உணர்வைப் பிரதிபலிப்பது: "இந்த வாரம் நான் ஒவ்வொரு நாளும் தாமதமாக வேலை செய்வதால் (உள்ளடக்கம்) நீங்கள் புறக்கணிக்கப்பட்டதாக உணர்கிறீர்கள் (உணர்வு)."' },
      actionStep: { en: 'Observe someone\'s body language today. Notice how 80% of their communication is non-verbal. Listen with your eyes and heart, not just your ears.', ta: 'இன்று ஒருவரின் உடல் மொழியைக் கவனியுங்கள். அவர்களின் தகவல்தொடர்புகளில் 80% எப்படி வாய்மொழி அல்லாதது என்பதைக் கவனியுங்கள். உங்கள் காதுகளால் மட்டுமல்ல, உங்கள் கண்கள் மற்றும் இதயத்தாலும் கேளுங்கள்.' },
      reflectionQuestion: { en: 'Do you rush in to "fix" people\'s problems before giving them the space to simply be heard?', ta: 'மனிதர்களுக்கு வெறுமனே செவிசாய்ப்பதற்கான இடத்தைக் கொடுப்பதற்கு முன்பாகவே, அவர்களின் பிரச்சினைகளைச் "சரிசெய்ய" நீங்கள் விரைகிறீர்களா?' }
    },
    {
      lessonNumber: 15,
      title: { en: 'Habit 6: Synergize', ta: 'பழக்கம் 6: ஒருங்கிணைந்து செயல்படுங்கள் (Synergize)' },
      explanation: { en: 'Synergy means that the whole is greater than the sum of its parts. It means that the relationship which the parts have to each other is a part in and of itself.', ta: 'ஒருங்கிணைந்து செயல்படுதல் (Synergy) என்பது முழுமையானது அதன் பகுதிகளின் கூட்டுத்தொகையை விடப் பெரியது என்பதாகும். ஒன்றுக்கொன்று உள்ள பகுதிகளின் உறவு தனக்குள் ஒரு பகுதி என்பதை இது குறிக்கிறது.' },
      whyItMatters: { en: 'When people communicate with respect and creativity, they create new alternatives that didn\'t exist before. 1 + 1 can equal 3, 10, or 100.', ta: 'மனிதர்கள் மரியாதையுடனும் படைப்பாற்றலுடனும் தொடர்பு கொள்ளும்போது, அவர்கள் முன்பு இல்லாத புதிய மாற்று வழிகளை உருவாக்குகிறார்கள். 1 + 1 என்பது 3, 10 அல்லது 100-க்குச் சமமாக இருக்கலாம்.' },
      example: { en: 'Two people arguing over whether to open a window for fresh air or close it to avoid a draft. Synergy is finding a "Third Alternative": opening a window in the *next* room, solving both problems perfectly.', ta: 'சுத்தமான காற்றுக்காக ஜன்னலைத் திறப்பதா அல்லது வரைவைத் தவிர்க்க அதை மூடுவதா என்று இருவர் வாதிடுகிறார்கள். ஒருங்கிணைந்து செயல்படுதல் என்பது "மூன்றாவது மாற்றீட்டைக்" கண்டுபிடிப்பதாகும்: *அடுத்த* அறையில் ஜன்னலைத் திறப்பது, இரண்டு பிரச்சினைகளையும் கச்சிதமாகத் தீர்க்கிறது.' },
      actionStep: { en: 'When faced with an "either/or" conflict today, refuse to compromise. Invite the other person to brainstorm a "Third Alternative" that gives both of you exactly what you want.', ta: 'இன்று ஒரு "இதுவா/அதுவா" மோதலை எதிர்கொள்ளும்போது, சமரசம் செய்ய மறுத்துவிடுங்கள். உங்கள் இருவருக்கும் என்ன வேண்டுமோ அதைச் சரியாகக் கொடுக்கும் "மூன்றாவது மாற்று வழியை" மூளைச்சலவை செய்ய மற்ற நபரை அழைக்கவும்.' },
      reflectionQuestion: { en: 'Do you view compromise (where both people lose a little) as the highest form of conflict resolution, instead of striving for synergy?', ta: 'ஒருங்கிணைந்து செயல்படப் பாடுபடுவதற்குப் பதிலாக, சமரசத்தை (இருவரும் சிறிதளவு இழக்கும் இடம்) மோதல் தீர்வின் மிக உயர்ந்த வடிவமாகப் பார்க்கிறீர்களா?' }
    },
    {
      lessonNumber: 16,
      title: { en: 'Valuing the Differences', ta: 'வேறுபாடுகளை மதிப்பிடுதல்' },
      explanation: { en: 'Valuing the mental, emotional, and psychological differences between people is the essence of synergy. The key to valuing those differences is to realize that all people see the world, not as it is, but as they are.', ta: 'மனிதர்களுக்கிடையேயான மன, உணர்ச்சி மற்றும் உளவியல் வேறுபாடுகளை மதிப்பிடுவதே ஒருங்கிணைந்து செயல்படுதலின் சாராம்சமாகும். அந்த வேறுபாடுகளை மதிப்பிடுவதற்கான திறவுகோல் என்னவென்றால், அனைத்து மனிதர்களும் உலகை உள்ளபடி பார்க்கவில்லை, அவர்கள் எப்படி இருக்கிறார்களோ அப்படியே பார்க்கிறார்கள் என்பதை உணர்வதாகும்.' },
      whyItMatters: { en: 'If two people have the exact same opinion, one of them is unnecessary. Sameness does not create synergy; difference does. You must cherish people who see the world differently than you.', ta: 'இரண்டு பேருக்கு ஒரே கருத்து இருந்தால், அவர்களில் ஒருவர் தேவையில்லை. ஒரே மாதிரியான தன்மை ஒருங்கிணைந்து செயல்படுதலை உருவாக்காது; வேறுபாடுதான் உருவாக்குகிறது. உங்களை விட உலக வித்தியாசமாகப் பார்க்கும் மனிதர்களை நீங்கள் மதிக்க வேண்டும்.' },
      example: { en: 'A highly logical, analytical CEO pairing up with a highly intuitive, creative Marketing Director. Instead of frustrating each other, they use their differences to cover each other\'s blind spots.', ta: 'மிகவும் தர்க்கரீதியான, பகுப்பாய்வு செய்யும் தலைமை நிர்வாக அதிகாரி, அதிக உள்ளுணர்வு மற்றும் ஆக்கபூர்வமான சந்தைப்படுத்தல் இயக்குநருடன் இணைவது. ஒருவரையொருவர் வெறுப்பேற்றுவதற்குப் பதிலாக, ஒருவரையொருவர் தவறவிடும் இடங்களை மறைக்கத் தங்களின் வேறுபாடுகளைப் பயன்படுத்துகிறார்கள்.' },
      actionStep: { en: 'Identify someone you work with who has a totally different operating style than you. Write down two ways their specific style makes the team stronger.', ta: 'உங்களை விட முற்றிலும் மாறுபட்ட செயல்பாட்டு பாணியைக் கொண்ட உங்களுடன் பணிபுரியும் ஒருவரைக் கண்டறியவும். அவர்களின் குறிப்பிட்ட பாணி அணியை எவ்வாறு வலிமையாக்குகிறது என்பதற்கான இரண்டு வழிகளை எழுதுங்கள்.' },
      reflectionQuestion: { en: 'Do you only surround yourself with people who agree with you, building an echo chamber instead of a synergistic team?', ta: 'ஒருங்கிணைந்த அணியை உருவாக்குவதற்குப் பதிலாக, உங்களுடன் உடன்படும் மனிதர்களை மட்டுமே நீங்கள் சுற்றி வைத்துக்கொண்டு, எதிரொலி அறையை உருவாக்குகிறீர்களா?' }
    },
    {
      lessonNumber: 17,
      title: { en: 'Habit 7: Sharpen the Saw', ta: 'பழக்கம் 7: ரம்பத்தைக் கூர்மைப்படுத்துங்கள் (Sharpen the Saw)' },
      explanation: { en: 'This is the habit of personal renewal. It means preserving and enhancing the greatest asset you have—you. It requires regularly renewing the four dimensions of your nature: Physical, Spiritual, Mental, and Social/Emotional.', ta: 'இது தனிப்பட்ட புதுப்பித்தலின் பழக்கமாகும். உங்களிடம் உள்ள மிகப்பெரிய சொத்தை—உங்களை—பாதுகாப்பதும் மேம்படுத்துவதும் இதன் பொருள். உங்களின் இயல்பின் நான்கு பரிமாணங்களைத் தொடர்ந்து புதுப்பிக்க வேண்டும்: உடல், ஆன்மீகம், மன மற்றும் சமூகம்/உணர்ச்சி.' },
      whyItMatters: { en: 'If you saw down a tree for hours without stopping to sharpen the saw, you will exhaust yourself and make no progress. Taking time to renew yourself makes all the other six habits possible.', ta: 'ரம்பத்தைக் கூர்மைப்படுத்த நிறுத்தாமல் பல மணிநேரம் நீங்கள் மரத்தை அறுத்தால், உங்களை நீங்களே சோர்வடையச் செய்வீர்கள், எந்த முன்னேற்றமும் இருக்காது. உங்களைப் புதுப்பித்துக் கொள்ள நேரம் ஒதுக்குவது மற்ற ஆறு பழக்கங்களையும் சாத்தியமாக்குகிறது.' },
      example: { en: 'Someone claiming they are "too busy driving to stop for gas." You must stop to exercise, read, meditate, and connect with loved ones, or your "engine" will fail.', ta: 'யாராவது "வண்டியை ஓட்டுவதில் மிகவும் பிஸியாக இருப்பதால் எரிபொருள் நிரப்ப நிறுத்த முடியாது" என்று கூறுவது போல. நீங்கள் உடற்பயிற்சி செய்ய, படிக்க, தியானம் செய்ய மற்றும் அன்புக்குரியவர்களுடன் இணைய நிறுத்த வேண்டும், இல்லையெனில் உங்கள் "இயந்திரம்" பழுதாகிவிடும்.' },
      actionStep: { en: 'Schedule exactly one hour this weekend for "Sharpening the Saw." Dedicate 15 mins to exercise, 15 mins to reading, 15 mins to meditation, and 15 mins to calling a friend.', ta: 'இந்த வார இறுதியில் "ரம்பத்தைக் கூர்மைப்படுத்துவதற்கு"ச் சரியாக ஒரு மணிநேரத்தை ஒதுக்குங்கள். உடற்பயிற்சி செய்ய 15 நிமிடங்கள், படிக்க 15 நிமிடங்கள், தியானத்திற்கு 15 நிமிடங்கள் மற்றும் ஒரு நண்பரை அழைக்க 15 நிமிடங்கள் ஒதுக்குங்கள்.' },
      reflectionQuestion: { en: 'Are you so busy trying to produce results that you are destroying your production capacity (your own health and well-being)?', ta: 'முடிவுகளை உருவாக்க முயற்சிப்பதில் நீங்கள் மிகவும் பிஸியாக இருப்பதனால், உங்களின் உற்பத்தித் திறனை (உங்கள் சொந்த உடல்நலம் மற்றும் நல்வாழ்வு) நீங்களே அழித்துக்கொள்கிறீர்களா?' }
    },
    {
      lessonNumber: 18,
      title: { en: 'The Upward Spiral', ta: 'மேல்நோக்கிய சுழல்' },
      explanation: { en: 'Renewal is the principle—and the process—that empowers us to move on an upward spiral of growth and change, of continuous improvement.', ta: 'புதுப்பித்தல் என்பது தொடர்ச்சியான முன்னேற்றம், வளர்ச்சி மற்றும் மாற்றத்தின் மேல்நோக்கிய சுழலில் செல்ல நமக்கு அதிகாரம் அளிக்கும் கொள்கை மற்றும் செயல்முறையாகும்.' },
      whyItMatters: { en: 'To move along the upward spiral requires us to learn, commit, and do on increasingly higher planes. We must continually educate and obey our conscience.', ta: 'மேல்நோக்கிய சுழற்சியில் செல்ல நாம் தொடர்ந்து உயர்ந்த தளங்களில் கற்கவும், உறுதியளிக்கவும், செயல்படவும் வேண்டும். நாம் தொடர்ந்து நமது மனசாட்சிக்குக் கற்பித்து அதற்குக் கீழ்ப்படிய வேண்டும்.' },
      example: { en: 'You learn a new communication skill, you commit to using it with your spouse, you do it. The relationship improves. You are now at a higher level, ready to learn the next skill.', ta: 'நீங்கள் ஒரு புதிய தகவல்தொடர்புத் திறனைக் கற்றுக்கொள்கிறீர்கள், உங்கள் வாழ்க்கைத்துணையுடன் அதைப் பயன்படுத்த உறுதியளிக்கிறீர்கள், நீங்கள் அதைச் செய்கிறீர்கள். உறவு மேம்படுகிறது. நீங்கள் இப்போது உயர் மட்டத்தில் உள்ளீர்கள், அடுத்தத் திறனைக் கற்றுக்கொள்ளத் தயாராக உள்ளீர்கள்.' },
      actionStep: { en: 'Pick one habit from this book you want to improve. Follow the "Learn, Commit, Do" process this week. Learn the principle, make a promise to yourself, and execute it.', ta: 'இந்தப் புத்தகத்திலிருந்து நீங்கள் மேம்படுத்த விரும்பும் ஒரு பழக்கத்தைத் தேர்ந்தெடுக்கவும். இந்த வாரம் "கற்றுக்கொள், உறுதியளி, செயல்படு" செயல்முறையைப் பின்பற்றவும். கொள்கையைக் கற்றுக்கொள்ளுங்கள், உங்களுக்கு நீங்களே வாக்குறுதி அளித்து, அதைச் செயல்படுத்துங்கள்.' },
      reflectionQuestion: { en: 'Are you stuck in a downward spiral of negativity, or are you actively pushing yourself upward through continuous learning and disciplined action?', ta: 'எதிர்மறையின் கீழ்நோக்கிய சுழலில் நீங்கள் சிக்கிக்கொண்டிருக்கிறீர்களா, அல்லது தொடர்ச்சியான கற்றல் மற்றும் ஒழுக்கமான செயல் மூலம் உங்களை நீங்களே தீவிரமாக மேல்நோக்கித் தள்ளுகிறீர்களா?' }
    },
    {
      lessonNumber: 19,
      title: { en: 'Inside-Out Approach', ta: 'உள்ளிருந்து-வெளி நோக்கிய அணுகுமுறை (Inside-Out Approach)' },
      explanation: { en: 'Inside-Out means to start first with self; even more fundamentally, to start with the most inside part of self—your paradigms, your character, and your motives.', ta: 'உள்ளிருந்து-வெளி நோக்கிய அணுகுமுறை என்பது முதலில் சுயத்துடன் தொடங்குவதாகும்; இன்னும் அடிப்படையாக, சுயத்தின் மிகவும் உள்ளே உள்ள பகுதியிலிருந்து-உங்கள் முன்மாதிரிகள், உங்கள் குணம் மற்றும் உங்கள் நோக்கங்கள்-தொடங்குவதாகும்.' },
      whyItMatters: { en: 'If you want to have a happy marriage, BE the kind of person who generates positive energy. If you want to be trusted, BE trustworthy. You cannot change the outside without changing the inside first.', ta: 'நீங்கள் ஒரு மகிழ்ச்சியான திருமண வாழ்க்கையை விரும்பினால், நேர்மறை ஆற்றலை உருவாக்கும் நபராக இருங்கள். நீங்கள் நம்பப்பட வேண்டும் என்றால், நம்பகமானவராக இருங்கள். முதலில் உள்ளே மாற்றாமல் வெளியே மாற்ற முடியாது.' },
      example: { en: 'Outside-In: "My team is lazy, they need to work harder." Inside-Out: "Am I communicating clearly? Am I inspiring them? I must improve my leadership first."', ta: 'வெளியிலிருந்து-உள் நோக்கிய அணுகுமுறை: "எனது குழு சோம்பேறித்தனமானது, அவர்கள் கடினமாக உழைக்க வேண்டும்." உள்ளிருந்து-வெளி நோக்கிய அணுகுமுறை: "நான் தெளிவாகத் தொடர்பு கொள்கிறேனா? நான் அவர்களை ஊக்குவிக்கிறேனா? நான் முதலில் எனது தலைமைத்துவத்தை மேம்படுத்த வேண்டும்."' },
      actionStep: { en: 'Take a problem you currently blame on someone else. Write down how *your* behavior or lack of clarity might be contributing to that exact problem.', ta: 'தற்போது நீங்கள் வேறொருவர் மீது பழி சுமத்தும் ஒரு பிரச்சினையை எடுத்துக்கொள்ளுங்கள். உங்களின் நடத்தை அல்லது தெளிவின்மை அந்தக் குறிப்பிட்ட பிரச்சினைக்கு எப்படிப் பங்களிக்கிறது என்பதை எழுதுங்கள்.' },
      reflectionQuestion: { en: 'Are you waiting for your spouse, your boss, or the economy to change before you can be happy or successful?', ta: 'நீங்கள் மகிழ்ச்சியாக அல்லது வெற்றிகரமாக இருப்பதற்கு முன் உங்களின் வாழ்க்கைத்துணை, உங்களின் முதலாளி அல்லது பொருளாதாரம் மாறும் என்று காத்திருக்கிறீர்களா?' }
    },
    {
      lessonNumber: 20,
      title: { en: 'Delegation: Gofer vs. Stewardship', ta: 'பிரித்துக்கொடுத்தல்: ஏவலாள் vs பொறுப்பாளர் (Gofer vs. Stewardship)' },
      explanation: { en: 'Gofer delegation dictates *methods* ("Go for this, go for that, do it this way"). Stewardship delegation focuses on *results* instead of methods, giving people a choice of method and making them responsible for results.', ta: 'ஏவலாள் பிரித்துக்கொடுத்தல் *முறைகளைக்* கட்டளையிடுகிறது ("இதற்காகச் செல், அதற்காகச் செல், இதை இப்படிச் செய்"). பொறுப்பாளர் பிரித்துக்கொடுத்தல் முறைகளுக்குப் பதிலாக *முடிவுகளில்* கவனம் செலுத்துகிறது, மனிதர்களுக்கு ஒரு முறையைத் தேர்ந்தெடுக்கும் வாய்ப்பை வழங்குகிறது மற்றும் முடிவுகளுக்கு அவர்களைப் பொறுப்பாக்குகிறது.' },
      whyItMatters: { en: 'Micromanagement (Gofer) ruins trust and limits growth. Stewardship builds trust, unleashes human creativity, and completely frees up the leader\'s time.', ta: 'நுண்-நிர்வாகம் (ஏவலாள்) நம்பிக்கையைச் சீரழிக்கிறது மற்றும் வளர்ச்சியைக் கட்டுப்படுத்துகிறது. பொறுப்பாளர் முறை நம்பிக்கையை உருவாக்குகிறது, மனிதப் படைப்பாற்றலைக் கட்டவிழ்த்து விடுகிறது, மற்றும் தலைவரின் நேரத்தை முழுமையாக விடுவிக்கிறது.' },
      example: { en: 'Gofer: "Mow the lawn, use this mower, go in these lines, empty the bag here." Stewardship: "I need the yard to look green and clean by Saturday. Here are the tools. You figure out how to do it."', ta: 'ஏவலாள்: "புல்வெளியை வெட்டுங்கள், இந்த அறுக்கும் இயந்திரத்தைப் பயன்படுத்துங்கள், இந்தக் கோடுகளில் செல்லுங்கள், பையை இங்கே காலி செய்யுங்கள்." பொறுப்பாளர்: "சனிக்கிழமைக்குள் முற்றம் பச்சையாகவும் சுத்தமாகவும் இருக்க வேண்டும். இதோ கருவிகள். அதை எப்படிச் செய்வது என்று நீங்கள் முடிவு செய்துகொள்ளுங்கள்."' },
      actionStep: { en: 'Delegate one task this week using Stewardship. Clearly define the desired *result*, set the guidelines, provide resources, establish accountability, and define the consequences. Then, step back.', ta: 'இந்தப் பொறுப்பாளர் முறையைப் பயன்படுத்தி இந்த வாரம் ஒரு பணியைப் பிரித்துக்கொடுங்கள். விரும்பிய *முடிவைத்* தெளிவாக வரையறுக்கவும், வழிகாட்டுதல்களை அமைக்கவும், வளங்களை வழங்கவும், பொறுப்புக்கூறலை நிறுவவும் மற்றும் விளைவுகளை வரையறுக்கவும். பிறகு, பின்வாங்குங்கள்.' },
      reflectionQuestion: { en: 'Are you exhausted because you insist on micromanaging the methods of everyone around you, instead of trusting them to deliver results?', ta: 'முடிவுகளை வழங்குவார்கள் என்று அவர்களை நம்புவதற்குப் பதிலாக, உங்களைச் சுற்றியுள்ள அனைவரின் முறைகளையும் நுண்-நிர்வாகம் (micromanage) செய்ய வற்புறுத்துவதால் நீங்கள் சோர்வடைகிறீர்களா?' }
    }
  ]
};

async function seed() {
  try {
    const mongoUri = process.env.MONGO_URI || process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/goalpilot';
    console.log(`Connecting to database at ${mongoUri}`);
    await mongoose.connect(mongoUri);
    
    // Check if it already exists
    const existing = await WisdomBook.findOne({ title: 'The 7 Habits of Highly Effective People' });
    if (existing) {
      console.log('The 7 Habits already exists. Deleting it to refresh...');
      await WisdomBook.deleteOne({ title: 'The 7 Habits of Highly Effective People' });
    }
    
    await WisdomBook.create(sevenHabitsBook);
    console.log('The 7 Habits added successfully with 20 lessons!');
    
    mongoose.connection.close();
  } catch (error) {
    console.error('Error seeding:', error);
    process.exit(1);
  }
}

seed();
