import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Register Tamil Font for PDF
Font.register({
  family: 'Noto Sans Tamil',
  src: 'https://fonts.gstatic.com/s/notosanstamil/v31/ieVc2YdFI3GCY6SyQy1KfStzYKZgzN1z4LKDbeZce-0429tBManUktuex7vGo40WoqQ.ttf'
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Noto Sans Tamil',
    backgroundColor: '#ffffff'
  },
  header: {
    marginBottom: 20,
    borderBottom: '2 solid #d946ef',
    paddingBottom: 10,
    alignItems: 'center'
  },
  title: {
    fontSize: 24,
    color: '#701a75',
    marginBottom: 5,
    fontWeight: 'bold'
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b'
  },
  section: {
    marginBottom: 20
  },
  sectionTitle: {
    fontSize: 14,
    color: '#d946ef',
    marginBottom: 10,
    borderBottom: '1 solid #e2e8f0',
    paddingBottom: 5
  },
  row: {
    flexDirection: 'row',
    marginBottom: 5
  },
  label: {
    width: 100,
    fontSize: 11,
    color: '#64748b'
  },
  value: {
    flex: 1,
    fontSize: 11,
    color: '#0f172a'
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    border: '1 solid #cbd5e1'
  },
  cell: {
    width: '25%',
    height: 60,
    border: '1 solid #cbd5e1',
    padding: 4,
    justifyContent: 'center',
    alignItems: 'center'
  },
  cellText: {
    fontSize: 10,
    color: '#334155',
    textAlign: 'center'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 10,
    color: '#94a3b8',
    borderTop: '1 solid #e2e8f0',
    paddingTop: 10
  }
});

const rasiTamilMap: Record<number, string> = {
  1: 'மேஷம்', 2: 'ரிஷபம்', 3: 'மிதுனம்', 4: 'கடகம்',
  5: 'சிம்மம்', 6: 'கன்னி', 7: 'துலாம்', 8: 'விருச்சிகம்',
  9: 'தனுசு', 10: 'மகரம்', 11: 'கும்பம்', 12: 'மீனம்'
};

const nakshatras = [
  'அஸ்வினி', 'பரணி', 'கிருத்திகை', 'ரோகிணி', 'மிருகசீரிடம்', 'திருவாதிரை', 
  'புனர்பூசம்', 'பூசம்', 'ஆயில்யம்', 'மகம்', 'பூரம்', 'உத்திரம்', 
  'அஸ்தம்', 'சித்திரை', 'சுவாதி', 'விசாகம்', 'அனுஷம்', 'கேட்டை', 
  'மூலம்', 'பூராடம்', 'உத்திராடம்', 'திருவோணம்', 'அவிட்டம்', 'சதயம்', 
  'பூரட்டாதி', 'உத்திரட்டாதி', 'ரேவதி'
];

const getPlanetName = (name: string) => {
  const map: Record<string, string> = {
    Sun: 'சூரியன்', Moon: 'சந்திரன்', Mars: 'செவ்வாய்', Mercury: 'புதன்',
    Jupiter: 'குரு', Venus: 'சுக்ரன்', Saturn: 'சனி', Rahu: 'ராகு', Ketu: 'கேது'
  };
  return map[name] || name;
};

interface AstrologyPDFProps {
  profile: any;
  chartData: any;
}

const AstrologyPDF = ({ profile, chartData }: AstrologyPDFProps) => {
  // Generate 4x4 Rasi Grid Data
  const gridCells = Array(12).fill(null);
  const rasiMap = [12, 1, 2, 3, 11, 0, 0, 4, 10, 0, 0, 5, 9, 8, 7, 6];
  
  const planetsBySign: Record<number, string[]> = {};
  for (let i = 1; i <= 12; i++) planetsBySign[i] = [];
  
  if (chartData?.planets) {
    chartData.planets.forEach((p: any) => {
      if (planetsBySign[p.sign]) {
        planetsBySign[p.sign].push(getPlanetName(p.name));
      }
    });
  }
  if (chartData?.ascendant) {
    const ascSign = Math.floor(chartData.ascendant.siderealLon / 30) + 1;
    if (planetsBySign[ascSign]) planetsBySign[ascSign].push('லக்னம்');
  }

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>ஜாதக குறிப்பு (Horoscope)</Text>
          <Text style={styles.subtitle}>Generated by GoalPilot Astrology</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>பிறப்பு விவரங்கள் (Birth Details)</Text>
          <View style={styles.row}>
            <Text style={styles.label}>பெயர் (Name):</Text>
            <Text style={styles.value}>{profile.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>பிறந்த தேதி (DOB):</Text>
            <Text style={styles.value}>{profile.dateOfBirth}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>நேரம் (Time):</Text>
            <Text style={styles.value}>{profile.timeOfBirth}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>பிறந்த ஊர் (Place):</Text>
            <Text style={styles.value}>{profile.placeOfBirth.city}</Text>
          </View>
        </View>

        {chartData && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>ஜோதிட விவரங்கள் (Astrological Details)</Text>
            <View style={styles.row}>
              <Text style={styles.label}>ராசி (Moon Sign):</Text>
              <Text style={styles.value}>{rasiTamilMap[chartData.moonSign]} ராசி</Text>
            </View>
            <View style={styles.row}>
              <Text style={styles.label}>நட்சத்திரம் (Star):</Text>
              <Text style={styles.value}>{nakshatras[chartData.moonNakshatra - 1]} நட்சத்திரம்</Text>
            </View>
          </View>
        )}

        {chartData && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>ராசி சக்கரம் (Rasi Chart)</Text>
            <View style={styles.grid}>
              {rasiMap.map((signNum, idx) => {
                if (signNum === 0) {
                  return (
                    <View key={idx} style={[styles.cell, { border: 'none' }]}>
                      {idx === 5 && <Text style={{fontSize: 16, color: '#d946ef', opacity: 0.2}}>ராசி</Text>}
                    </View>
                  );
                }
                const planetsHere = planetsBySign[signNum] || [];
                return (
                  <View key={idx} style={styles.cell}>
                    <Text style={{fontSize: 8, color: '#94a3b8', position: 'absolute', top: 2, left: 2}}>
                      {rasiTamilMap[signNum]}
                    </Text>
                    <View style={{marginTop: 8}}>
                      {planetsHere.map((p, i) => (
                        <Text key={i} style={styles.cellText}>{p}</Text>
                      ))}
                    </View>
                  </View>
                );
              })}
            </View>
          </View>
        )}

        <View style={styles.footer}>
          <Text>GoalPilot - Life Operating System</Text>
        </View>
      </Page>
    </Document>
  );
};

export default AstrologyPDF;
