export const DEFAULT_UNLOCKED_MODULES = [
  'Dashboard',
  'Goals',
  'Update Hours',
  'Tasks',
  'Habits',
  'Stoicism',
  'Settings',
  'Mission Control',
  'TickTick Planner',
  'Tools',
  'Intelligence Hub',
  'Market Intelligence',
  'Combat Academy',
  'Brain Academy',
  'Wisdom Library',
  'Life Wealth & Dream OS',
  'Vocabulary Builder',
  '🔮 ஜோதிடம்'
];
